spring.application.name=ecommerce-backend

spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_website?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.port=8080

# secret key = furkandemirci
jwt.secret=se+mmNHJ7/5SA8OTx83bedLRkfsUc1LBkth8gg6wOXs=

# 4 saat
jwt.expiration=14400000
# 12 saat
jwt.refresh-token.expiration=43200000

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
