package com.furkan.enums;

public enum OrderStatus {

    PENDING,
    CONFIRMED,
    CANCELLED,
    SHIPPED,
    DELIVERED,
    PARTIALLY_SHIPPED,
    PARTIALLY_DELIVERED,
    PARTIALLY_RETURN_REQUESTED,
    PARTIALLY_REFUNDED,
    RETURN_REQUESTED,
    REFUNDED
}
